files/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from profiles import views as profile_views

urlpatterns = [
    path('', include('frontend.urls')),
    path('profile/', include('profiles.urls')),
    path('register/', profile_views.register, name='register'),
    path('reservations/', include('reservations.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from profiles import views as profiles_views
from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.index, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='profiles/logout.html'), name='logout'),
    path('register/', profiles_views.register, name='register'),
]

profiles/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('bands', views.band_list, name='band-list'),
    path('band-creation/', views.band_creation, name='band-creation'),
    path('edit-band/<str:id>/', views.edit_band, name='edit-band'),
    path('delete-band/<str:id>/', views.delete_band, name='delete-band'),
]
    

reservations/urls.py
from django.urls import path
from . import views


app_name = 'reservations'
urlpatterns = [
    path('', views.reservations_list, name='lista'),
    path('make/', views.make_res, name='make'),
    path('success/', views.success, name='success'),
    path('my-res/', views.my_res, name='my-res'),
]

bands/models.py
from django.db import models
from django.contrib.auth.models import User

class Band(models.Model):
    name = models.CharField(max_length=200, verbose_name='nombre')
    img = models.ImageField(verbose_name='foto', upload_to='bands_pics', default='default-band.jpg', null=True, blank=True)
    genre = models.CharField(max_length=200, verbose_name='género', blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} de {self.owner}_id: {self.owner.id}'

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(verbose_name='profile pic',
                            upload_to='profile_pics',
                            default='default-profile.jpg',
                            )

    def __str__(self):
        return f'{self.user} Profile'

bands/forms.py
from django import forms
from .models import Band

class CreateBandForm(forms.ModelForm):
    model = Band
    fields = ['name', 'genre', 'img']

profiles/forms.py
from django import forms
from bands.models import Band
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class CreateBandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = ['name', 'genre', 'img']
        required = []

bands/views.py
from django.shortcuts import render

def create_band(request):
    
    context = {}
    return render(request, 'profile/create_band.html', context)

profiles/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from reservations.models import Reservation
from bands.models import Band
from .forms import CreateBandForm, UserRegisterForm

def register(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Cuenta creada para {username}! :)')
            return redirect('frontend:login')

    context = {
        'form':form
    }
    return render(request, 'profiles/register.html', context)

@login_required()
def profile(request):
    user = User.objects.get(id=request.user.id)
    bands = Band.objects.filter(owner=user)
    user_reservation_count = Reservation.objects.filter(owner=user).count()
    banda_favorita = bands[:1]

    context = {
        'user' : user,
        'bands': bands,
        'user_reservation_count':user_reservation_count,
        'banda_favorita':banda_favorita,
    }
    return render(request, 'profiles/profile.html', context)

@login_required()
def band_list(request):
    user = User.objects.get(id=request.user.id)
    bands = Band.objects.filter(owner=user)

    context = {
        'bands': bands,
    }
    return render(request, 'profiles/bands.html', context)
    
@login_required()
def band_creation(request):
    form = CreateBandForm()
    user = User.objects.get(pk=request.user.id)
    if request.method == 'POST':
        form = CreateBandForm(request.POST, instance=user, files=request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            newband = Band(name=cd['name'], genre=cd['genre'], owner=user)
            newband.save()
            return redirect('profiles:profile')

    context = {
        'form': form,
    }
    return render(request, 'profiles/create_band.html', context)

@login_required()
def edit_band(request, id):
    band = Band.objects.get(pk=id)
    form = CreateBandForm(instance=band)
    if request.method == 'POST':
        form = CreateBandForm(request.POST, instance=band, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('profiles:profile')
    
    return render(request, 'profiles/edit_band.html', {'form':form})

@login_required()
def delete_band(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('profiles:band-list')

    return render(request, 'profiles/delete_band.html', {'band':band})

profiles/templates/profiles/bands.html
{% extends 'frontend/base.html' %}

{% block title %}
{% endblock title %}


{% block content %}
<div class="body-body">
    <div class="container">
        {% if bands %}
        {% for band in bands %}
        <div class="band-card">
            <div class="band-content">
                <div class="band-pic">
                    <img id="band-pic-circle" src="{{band.img.url}}" alt="Foto de perfil">
                </div>
                <div class="band-body-content">
                    <h2>{{band.name.title}}</h2>
                </div>
                <div class="band-footer-content">
                    <small><a href="{% url 'profiles:edit-band' band.id %}">Editar banda</a></small>
                    <p>~</p>
                    <small><a href="{% url 'profiles:delete-band' band.id %}">Borrar</a></small>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h1>No tienes bandas, agrega una <a href="{% url 'profiles:band-creation' %}">aquí</a></h1>
        {% endif %}
    </div>



</div>
{% endblock content %}

profiles/templates/profiles/create_band.html
{% extends 'frontend/base.html' %}

{% load widget_tweaks %}

{% block title %}
<title>Crear banda</title>
{% endblock title %}

{% block content %}
<div class="body-body">
    <div class="form-container">
        <div class="form-card">
            <div class="form-card-content">
                <h1>Bands</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-txt_field">
                        {% render_field form.name type="text" placeholder="Name"%}
                    </div>
                    <div class="form-txt_field">
                        {% render_field form.genre type="text" placeholder="Genre"%}
                    </div>
                    <div class="form-file-field">
                        {% render_field form.img type="file" placeholder="Imagen" %}
                    </div>
                    <input class="form-submit" type="submit" value="Crear">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/delete_band.html
{% extends 'frontend/base.html' %}

{% load widget_tweaks %}

{% block title %}
{% endblock title %}

{% block content %}
<div class="body-body">

    <form method="POST">
        {% csrf_token %}
        <h2>Seguro quieres borrar "{{band.name}}"</h2>
        <input type="submit" value="SI">
        <a href="{% url 'profiles:band-list' %}">NO</a>
    </form>
</div>
{% endblock content %}

profiles/templates/profiles/edit_band.html
{% extends 'frontend/base.html' %}

{% load widget_tweaks %}

{% block title %}
<title>Edit band</title>
{% endblock title %}

{% block content %}
<div class="body-body">
    <div class="form-container">
        <div class="form-card">
            <div class="form-card-content">
                <h1>Bands</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-txt_field">
                        {% render_field form.name type="text" placeholder="Name"%}
                    </div>
                    <div class="form-txt_field">
                        {% render_field form.genre type="text" placeholder="Genre"%}
                    </div>
                    <div class="form-file-field">
                        {% render_field form.img type="file" placeholder="Imagen" %}
                    </div>
                    <input class="form-submit" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/login.html
{% extends 'frontend/base.html' %}
{% load widget_tweaks %}
{% block title %}
<title>Login</title>
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<div class="body-body">
    <h1 style="color:white;">YA COMPLETASTE EL REGISTRO :)</h1>
</div>
{% else %}

<div class="body-body">
    <div class="form-container">
        <div class="form-card">
            <div class="form-card-content">
                <h1>Login</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-txt_field">
                        {% render_field form.username type="text" placeholder="Username"%}
                    </div>
                    <div class="form-txt_field">
                        {% render_field form.password type="password" placeholder="Password"%}
                    </div>
                    <div class="form-forgot-pass">
                        <small> Olvidaste tu pass? <a href="#">Recuperar</a></small>
                    </div>
                    <input class="form-submit" type="submit" value="Entrar">
                    <div class="form-footer">
                        <small>No tienes cuenta? Créala <a href="{% url 'frontend:register' %}">aquí</a> </small>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}


{% endblock content %}

profiles/templates/profiles/logout.html
{% extends 'frontend/base.html' %}

{% block title %}
{% endblock title %}


{% block content %}
<div class="body-body">
    <div class="logout-frame">
        <h1>Logout completado</h1>
        <div class="login-question">
            <h4>Volver a <a href="{% url 'frontend:login' %}">ingresar</a></h4>
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/profile.html
{% extends 'frontend/base.html' %}

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}
<div class="body-body">

    <div class="main-container">
        <div class="greeting-wrapper">
            <h3>Profile</h3>
        </div>
        <div class="card-container">
            <div class="card-wrapper">
                <div class="left-column">
                    <div class="profile-pic">
                        <img id="profile-pic-circle" src="{{user.profile.pic.url}}" alt="Foto de perfil">
                    </div>
                    <div class="personal-info">
                        <h4>{{user.username.capitalize}}</h4>
                        <h6>{{user.profile.rol.capitalize}}</h6>
                    </div>
                    <div class="profile-links">
                        <div class="a-profile">
                            <a href="{% url 'reservations:make' %}">Make reservation</a>
                        </div>
                        <div class="a-profile">
                            <a href="{% url 'reservations:my-res' %}">My Reservations</a>

                        </div>
                        <div class="a-profile">
                            <a href="{% url 'profiles:band-list' %}">My Bands</a>
                        </div>
                    </div>
                </div>
                <div class="right-column">
                    <div class="reservations-info">
                        <div class="reservas-hechas">
                            <h4>TOTAL DE RESERVAS</h4>
                            <h1 class="profile-big-num">{{user_reservation_count}}</h1>
                        </div>
                        <div class="reservas-hechas">
                            <h4>HORAS ENSAYADAS</h4>
                            <h1 class="profile-big-num">0</h1>
                        </div>
                    </div>
                    <div class="bands-info">
                        <div class="profile-bands">
                            <h4>BANDA FAVORITA</h4>
                            {% if banda_favorita %}
                            <div class="profile-band-container">
                                <div class="profile-band-card">
                                    {% for band in banda_favorita %}
                                    <div class="profile-pic">
                                        <img id="profile-pic-circle" src="{{band.img.url}}" alt="Foto de perfil">
                                    </div>
                                    <div class="profile-band-info">
                                        <p>Name: {{band.name.title}}</p>
                                        <p>Genre: {{band.genre.title}}</p>
                                    </div>
                                    {% endfor %}
                                    {% else %}
                                    <h5>No tienes bandas.</h5>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endblock content %}

profiles/templates/profiles/register.html
{% extends 'frontend/base.html' %}
{% load widget_tweaks %}
{% block title %}
<title>Sign up</title>
{% endblock title %}

{% block content %}
<div class="body-body">
    {% if user.is_authenticated %}

    <h2 id="register-denied-h1">Para crear una cuenta es necesario desloguearse.</h2>

    {% else %}
    <div class="form-container">
        <div class="form-card">
            <div class="form-card-content">
                <h1>Register</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-txt_field">
                        {% render_field form.username type="text" placeholder="Username"%}
                    </div>
                    <div class="form-txt_field">
                        {% render_field form.email type="text" placeholder="Email"%}
                    </div>
                    <div class="form-txt_field">
                        {% render_field form.password1 type="password" placeholder="Password"%}
                    </div>
                    <div class="form-txt_field">
                        {% render_field form.password2 type="password" placeholder="Confirm Password"%}
                    </div>
                    <div class="form-forgot-pass">
                        <small> Olvidaste tu pass? <a href="#">Recuperar</a></small>
                    </div>
                    <input class="form-submit" type="submit" value="Entrar">
                    <div class="form-footer">
                        <small>Ya tienes cuenta? Entra <a href="{% url 'frontend:login' %}">aquí</a> </small>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
</div>

{% endblock content %}