files/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from profiles import views as profile_views

urlpatterns = [
    path('', include('frontend.urls')),
    path('profile/', include('profiles.urls')),
    path('register/', profile_views.register, name='register'),
    path('reservations/', include('reservations.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from profiles import views as profiles_views
from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.index, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='profiles/logout.html'), name='logout'),
    path('register/', profiles_views.register, name='register'),
]

profiles/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('bands', views.band_list, name='band-list'),
    path('band-creation/', views.band_creation, name='band-creation'),
    path('edit-band/<str:id>/', views.edit_band, name='edit-band'),
    path('delete-band/<str:id>/', views.delete_band, name='delete-band'),
]
    

reservations/urls.py
from django.urls import path
from . import views


app_name = 'reservations'
urlpatterns = [
    path('', views.reservations_list, name='lista'),
    path('make/', views.make_res, name='make'),
    path('success/', views.success, name='success'),
    path('my-res/', views.my_res, name='my-res'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'frontend/index.html')


def contact(request):
    pass
# TODO: Hacer front:contact view

frontend/templates/frontend/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/salavictoriaicon.png' %}">
    {% block title %}
    {% endblock title %}
</head>

<body>
    <header>
        <div class="nav-container">
            <nav>
                <a id="logo" href="{% url 'frontend:index' %}">
                    <h1>sala victoria</h1>
                </a>
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'profiles:profile' %}">Perfil</a></li>
                    <li><a href="{% url 'reservations:lista' %}">Reservas</a></li>
                    <li><a href="{% url 'frontend:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'frontend:login' %}">Entrar</a></li>
                    <li><a href="{% url 'frontend:register' %}">Registrarme</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {% if messages %}
        <div class="messages-container">
            {% for message in messages %}
            <div class="message-alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </header>

    {% block content %}
    {% endblock content %}
    <!-- Option 1: Bootstrap Bundle with Popper -->
</body>

</html>

frontend/templates/frontend/index.html
{% extends 'frontend/base.html' %}

{% block title %}
<title>Victoria</title>
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<div class="body-body">
    <div class="container">
        <div class="card">
            <div class="content">
                <div class="content-top">
                    <h2>MEMBER</h2>
                    <h2>PROFILE</h2>
                </div>
                <div class="divider"></div>
                <div class="content-bot">
                    <h3>Personal Profle</h3>
                    <p>Toma el control de tu espacio personal y accede a tu perfil.
                    </p>
                    <hr>
                    <p>Puedes revisar tus reservas y bandas</p>
                    <a href="{% url 'profiles:profile' %}">Entrar</a>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
        <div class="card-bands">
            <div class="content">
                <div class="content-top">
                    <h2>BAND</h2>
                    <h2>MANAGER</h2>
                </div>
                <div class="divider"></div>
                <div class="content-bot">
                    <h3>Band manager</h3>
                    <p>Crea tu banda, añade los integrantes y su rol. Lleva el control del tiempo que has ensayado
                        con cada una.</p>
                    <hr>
                    <p>Entra y lleva el control de tus bandas dentro del perfil.</p>
                    <a href="{% url 'profiles:band-list' %}">Entrar</a>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
        <div class="card-reservations">
            <div class="content">
                <div class="content-top">
                    <h2>RERSERVATION</h2>
                </div>
                <div class="divider"></div>
                <div class="content-bot">
                    <h3>Reservations</h3>
                    <p>Ten el control de qué día y a qué hora vas a ensayar. </p>
                    <hr>
                    <p>Nuestro sistema te deja hacer track de las horas ensayadas con cualquiera de tus bandas</p>
                    <a href="{% url 'reservations:lista' %}">Entrar</a>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="body-body">
    <div class="container">
        <div class="card">
            <div class="content">
                <div class="content-top">
                    <h2>BAND</h2>
                    <h2>MEMBERS</h2>
                </div>
                <div class="divider"></div>
                <div class="content-bot">
                    <h3>Band member</h3>
                    <p>Únete a la familia de músicos de Occidente que trabajan su música en este espacio.
                    </p>
                    <hr>
                    <p>Crea una cuenta y maneja tus bandas y tus reservaciones.</p>
                    <a href="{% url 'frontend:register' %}">Crear cuenta</a>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
        <div class="card-bands">
            <div class="content">
                <div class="content-top">
                    <h2>BAND</h2>
                    <h2>MANAGER</h2>
                </div>
                <div class="divider"></div>
                <div class="content-bot">
                    <h3>Band manager</h3>
                    <p>Crea tu banda, añade los integrantes y su rol. Lleva el control del tiempo que has ensayado
                        con
                        cada una.</p>
                    <hr>
                    <p>Entra y lleva el control de tus bandas dentro del perfil.</p>
                    <a href="{% url 'profiles:band-creation' %}">Entrar</a>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
        <div class="card-reservations">
            <div class="content">
                <div class="content-top">
                    <h2>RERSERVATION</h2>
                </div>
                <div class="divider"></div>
                <div class="content-bot">
                    <h3>Reservations</h3>
                    <p>Ten el control de qué día y a qué hora vas a ensayar. </p>
                    <hr>
                    <p>Nuestro sistema te deja hacer track de las horas ensayadas con cualquiera de tus bandas</p>
                    <a href="{% url 'reservations:lista' %}">Entrar</a>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

frontend/templates/frontend/newfile.html
{% extends 'frontend/base.html' %}

{% block title %}
{% endblock title %}

<div class="body-body"></div>
{% block content %}
{% endblock content %}